### ISSUE TITLE
Description of team members

### ISSUE THREAD

**Issue by AbelG101** [AbelG101/Recipe-app#9]
## Kanban board link:
- [Click here](https://github.com/users/AbelG101/projects/2)
## Team members
- We are a group of 2 people
    - Team member 1: @AbelG101, 
    - Team member 2: @betses

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @AbelG101 and @betses,

Good job so far!
✔️ Kanban columns are well created
✔️ Tasks are properly distributed
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] You are missing an issue that caters to this task. Kindly add it.

  ![n-2](https://user-images.githubusercontent.com/36542986/207015118-65af6ee0-8329-4e37-9198-92ff4be754ce.jpg)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AbelG101** [comment]
Hello👋 @TedLivist, My partner and I have agreed to check for N+1 problems anytime we make queries to fetch data. That's why we haven't added it as a separate card. I'll add it to every card as a requirement.

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @AbelG101 and @betses,

✔️ Tasks complexities are well distributed

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
